# Generated by Django 3.2.6 on 2022-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isay', '0008_auto_20220525_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.CharField(choices=[('Counseling', 'Counseling'), ('Psychological Testing', 'Psychological Testing'), ('Career Guidance, Graduate Placement and Follow-up', 'Career Guidance, Graduate Placement and Follow-up'), ('Human Development Services', 'Human Development Services'), ('Peer Facilitating Program', 'Peer Facilitating Program')], default='Counseling', max_length=100),
        ),
    ]
