# Generated by Django 3.2.6 on 2022-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isay', '0012_auto_20220526_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='who_accepted',
            new_name='who_accepted_f',
        ),
        migrations.AddField(
            model_name='appointment',
            name='who_accepted_n',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
