# Generated by Django 3.2.6 on 2022-05-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isay', '0013_auto_20220526_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='who_accepted_n',
            new_name='who_accepted_l',
        ),
    ]
