# Generated by Django 3.2.6 on 2022-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isay', '0015_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='college',
            field=models.CharField(choices=[('CAS', 'CAS'), ('SOTECH', 'SOTECH'), ('CFOS', 'CFOS'), ('UPVHS', 'UPVHS'), ('UPVTC', 'UPVTC')], default='CAS', max_length=100),
            preserve_default=False,
        ),
    ]
