# Generated by Django 3.2.6 on 2022-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isay', '0016_appointment_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='college',
            field=models.CharField(choices=[('CAS', 'CAS'), ('CM', 'CM'), ('SOTECH', 'SOTECH'), ('CFOS', 'CFOS'), ('UPVHS', 'UPVHS'), ('UPVTC', 'UPVTC')], max_length=100),
        ),
    ]
